# Generated by Django 4.1.4 on 2022-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=99)),
                ('city', models.CharField(max_length=99)),
                ('marks', models.FloatField()),
                ('recorded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
